#!/usr/bin/env zsh

root_dir=$(git rev-parse --show-toplevel)
example_dir="$root_dir/examples/$1/"
cache_dir="$root_dir/.plugin-cache" # TODO: make cache work
cmd=(-it nocksock/neovim-run ${2:-nvim})

zparseopts -D -E -F -A opts h=help -help=help w=watch -watch=watch -nocache=nocache f=nocache

if [[ -z $1 || ${help} ]]; then
	cat <<-EOF
		Usage: $0 <name-of-example>
			-h, --help    Show this help message
			-w, --watch   Watch the example directory for changes
	EOF
	test ${help} && exit 0
	exit 1
fi

if [[ $watch ]]; then
	fd | entr -s "tmux killw -t docker ; tmux neww -d -n docker examples/run $1"
	exit
fi

if [[ ! $nocache ]]; then
	cache=(-v $cache_dir:/root/.local/share/nvim/site/pack/baggage/opt/)
fi

if [[ ! -d "$example_dir" ]]; then
	echo "Example directory not found: $example_dir"
	exit 1
fi

# the install example uses the remote repo for the full install routine
if [[ $1 == "install" ]]; then
 docker run                            \
	-v "$example_dir":/root/.config/nvim \
	$cache                               \
	$cmd
 exit 0
fi

# the install-local example performs the install routine using this repo
if [[ $1 == "install-local" ]]; then
 docker run                             \
	-v "$example_dir":/root/.config/nvim  \
	-v "$root_dir/.git":/root/baggage.git \
	$cache                                \
	$cmd
 exit 0
fi


# all other examples have it pre-installed via mount
docker run                                                                    \
	-v "$example_dir":/root/.config/nvim                                        \
	-v "$root_dir":/root/baggage.nvim                                           \
	-v "$root_dir":/root/.local/share/nvim/site/pack/baggage/start/baggage.nvim \
	$cmd
